#!/usr/bin/env bash
# Install Puppet and puppet-lint

sudo apt-get -y update
sudo apt-get -y upgrade

# Install puppet
sudo apt-get install -y ruby=1:2.7+1 --allow-downgrades
sudo apt-get install -y ruby-augeas
sudo apt-get install -y ruby-shadow
sudo apt-get install -y puppet

# Install puppet-lint
gem install puppet-lint
