#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

ERROR_PAGE='error_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n'

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "40i $ERROR_PAGE" /etc/nginx/sites-available/default
sudo service nginx restart
