#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

sudo touch /tmp/my_process
sudo chmod 777 /tmp/my_process

while true; do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done

