#!/usr/bin/env bash
# This script for displays numbers from 1 to 100
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number

FB_3_5="FizzBuzz"
F_3="Fizz"
B_5="Buzz"
COUNT=1
END_COUNT=100

while test $COUNT -le $END_COUNT; do
	if [ $((COUNT % 3)) == 0 ] && [ $((COUNT % 5)) == 0 ]; then
		echo "$FB_3_5"
	elif [ $((COUNT % 3)) -eq 0 ]; then
		echo "$F_3"
	elif [ $((COUNT % 5)) -eq 0 ]; then
		echo "$B_5"
	else
		echo "$COUNT"
	fi
	COUNT=$((COUNT + 1))
done

