#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
#	username
#	user id
#	Home directory path for the user

while read -r line; do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homedir=$(echo "$line" | cut -d: -f6)
	echo "$username:$userid:$homedir"
done < /etc/passwd

