#!/usr/bin/env bash
# Displays the content of the file /etc/passwd

while read -r line; do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	groupid=$(echo "$line" | cut -d: -f4)
	homedir=$(echo "$line" | cut -d: -f6)
	pass=$(echo "$line" | cut -d: -f2)
	cmd=$(echo "$line" | cut -d: -f7)
	userinfo=$(echo "$line" | cut -d: -f5)
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmd. $userid's place is protected by the passcode $pass, more info about the user here: $userinfo"
done < /etc/passwd

