#!/usr/bin/env bash
# This script for loops from 1 to 10 and
#	displays bad luck for the 4th loop iteration
#	displays good luck for the 8th loop iteration
#	displays Best School for the other iterations

BAD="bad luck"
GOOD="good luck"
BEST="Best School"
COUNT=0

while test $COUNT -lt 10; do
	if test $COUNT -eq 3; then
		echo "$BAD"
	elif test $COUNT -eq 7; then
		echo "$GOOD"
	else
		echo "$BEST"
	fi
	COUNT=$((COUNT + 1))
done

