#!/usr/bin/env bash
# This script for displays numbers from 1 to 20 and
#	displays 4 and then bad luck from China for the 4th loop iteration
#	displays 9 and then bad luck from Japan for the 9th loop iteration
#	displays 17 and then bad luck from Italy for the 17th loop iteration

BAD_4="bad luck from China"
BAD_9="bad luck from Japan"
BAD_17="bad luck from Italy"
COUNT=1

while test $COUNT -le 20; do
	echo "$COUNT"
	case $COUNT in
		4) echo "$BAD_4";;
		9) echo "$BAD_9";;
		17) echo "$BAD_17";;
	esac
	COUNT=$((COUNT + 1))
done

