#!/usr/bin/bash
# install the ufw firewall and setup a few rules

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install ufw
sudo ufw enable
sudo ufw default deny
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw reload

