#!/usr/bin/env bash
# uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

private_key="~/.ssh/school"
user="ubuntu"
server="54.160.79.52"

ssh -i "$private_key" "$user@$server"

